### ISSUE TITLE
I always get the error when installing 

### ISSUE THREAD

**Issue by nikivdev** [SamVerschueren/generator-alfred#2]
![2016-11-05 at 17 32](https://cloud.githubusercontent.com/assets/6391776/20031814/d0567384-a37d-11e6-8494-09c8b8dab455.png)

I am quite new to node.js and javascript. I had the same issue with [alfy](https://github.com/sindresorhus/alfy). Can anyone help solve this?

Thank you for any help.

**Comment by SamVerschueren** [comment]
What command did you ran? Doesn't seem like it has anything to do with this generator.

**Comment by nikivdev** [comment]
Yeah, my bad. I had to do npm init first and then run npm install --save command.

I think it works now. This generator is pretty awesome. Thank you.
