### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by alexilyaev** [SamVerschueren/generator-alfred#7]
Hi, thanks for this repo.

Would appreciate some docs.  
It's my first time creating an Alfred Workflow, got here through [Alfy](https://github.com/sindresorhus/alfy), but I didn't get how to create the actual workflow and connect it to the generated code?

**Comment by martisj** [comment]
Generator-alfred is a generator for yeoman. Sooo you need [yo](https://github.com/yeoman/yo) _**and generator-alfred**_

Then you run `yo alfred`
